### ISSUE TITLE
it's not dark anymore

### ISSUE THREAD

**Issue by radioman** [stormbreakerbg/Dark-youtube-plugin-chrome#26]
youtube idiot coders changed they div ids ;/

**Comment by stormbreakerbg** [comment]
Hi,

Thanks for reporting. Can you please attach a screenshot of the problem? Sometimes YouTube does A/B testing so only part of the users get the changes.

Also, those "youtube idiot coders" are doing their job and improving their site. They are not obligated to maintain compatibility with third-party css modifications.

**Comment by radioman** [comment]
thats why they are idiots, fucking white background...
...anyway it's dark again, who knows why, i'll reopen if it changes again, thanks bro for this plugin!
