### ISSUE TITLE
Notification Options Checkboxes Don't render

### ISSUE THREAD

**Issue by Pythor** [stormbreakerbg/Dark-youtube-plugin-chrome#27]
If you have Dark enabled, and click on the options button (little gear icon) next to the Subscribed button, the menu that opens up has a checkbox, but with dark enabled, you can't actually see the checkmark.  This makes it impossible to know if you have notifications enabled or not.

The same issue happens if you go into your accounts settings to manage all your notification options at the same time.

**Comment by NSDex** [comment]
On line 590 of dark.css we are applying a style override to *all* input elements.  This is overriding the 'checked' style on that checkbox.  I'm not sure why we style all input elements (git log shows the offending line in from the first commit) but a more specific elector should have been used.

I'll try removing it from my copy and see what, if anything, breaks.
