### ISSUE TITLE
Main area of video manager page is not dark and just looks weird in general

### ISSUE THREAD

**Issue by matt3541** [stormbreakerbg/Dark-youtube-plugin-chrome#29]
See screenshot

![ss 2016-06-20 at 01 49 25](https://cloud.githubusercontent.com/assets/11934593/16188332/c20ee5b0-3689-11e6-859f-17ac6b53c49a.jpg)

Everything else seems to be working nicely, thank you for the extension!

**Comment by NSDex** [comment]
Hey Matt

What's the URL of this page?  https://www.youtube.com/user/<username>/videos looks fine for me.

**Comment by Dancanplay** [comment]
It's the video manager, I will take a look at it.

**Comment by matt3541** [comment]
It's https://www.youtube.com/my_videos?o=U

**Comment by link07** [comment]
I think that's one of the pages I started working on themeing, but RL made me stop before I finished and I kinda forgot about it.  It's over at the [Theme Dashboard branch of my fork](https://github.com/link07/Dark-youtube-plugin-chrome/tree/Theme-Dashboard) if anyone wants to continue it, as I won't have time this week.

**Comment by mikesterific** [comment]
I couldn't create a pull request, but the following code in dark.css will fix the issue:
/* Parent Container */
#page-container
{
    background-color: #1b1b1b !important;
}

**Comment by mikesterific** [comment]
Actually this worked a little better, using on tampermonkey now, so far so good
#body-container
{
background-color: #1b1b1b !important;
}
