### ISSUE TITLE
Link color too dark

### ISSUE THREAD

**Issue by proimage** [stormbreakerbg/Dark-youtube-plugin-chrome#32]
Hey, love the plugin! I forked the entire thing and was going to make this change myself, but realized it's  such a simple change that doing so didn't make sense.

Could you change the blue link color to be lighter? I played around in DevTools and `#68b4ee` seems to work great.

The problem is that the current darkish blue doesn't have enough contrast with the black background to be easily visible. It kinda requires an eye strain and a squint, if you know what I mean. ;) Thanks!

**Comment by Dancanplay** [comment]
Preview: 
![image](https://cloud.githubusercontent.com/assets/9385112/18220588/f02ccfe6-7173-11e6-84ab-6dcb7cb8f439.png)

**Comment by proimage** [comment]
I guess. That should definitely help, in any case. :) Much grass!
