### ISSUE TITLE
#masthead-search not inverted

### ISSUE THREAD

**Issue by BrandonRaggett** [stormbreakerbg/Dark-youtube-plugin-chrome#33]
Just noticed that this element is no longer inverted, and margin has been added.
This only seems to be the case when signed in. Incognito looks the same as it used to.

Fixed in stylish by setting background-color to transparent and removing margin.

**Comment by Dancanplay** [comment]
You have version from chrome web store? I know I fixed it in previous commit

**Comment by BrandonRaggett** [comment]
Yes, I have the chrome web store version. 
Probably doesn't make much difference, but my chromium version is: Version 51.0.2704.79 Ubuntu 16.04 (64-bit)

Checked on my mac too, and it's the same problem.

**Comment by Dancanplay** [comment]
You'll need to wait until stormbreaker makes another version, hopefully he notices this, and makes one.

**Comment by stormbreakerbg** [comment]
Uploaded! You have done a lot of work, it's great!

@Dancanplay and @NSDex, you can ping me any time you want me to do a release, just mention me with my handle here :) And again, thanks for keeping this updated!

@BrandonRaggett, I'm closing this issue, feel free to reopen it if it is still present after the update.
