### ISSUE TITLE
"native dark mode" Doesn't exist when Polymer is disabled...

### ISSUE THREAD

**Issue by FatheredPuma81** [stormbreakerbg/Dark-youtube-plugin-chrome#62]
So how do I use this "native dark mode" when I have polymer disabled which reverts YT back to it's old style?
I assume this is the "Dark Mode for YouTube" that was the Chrome extension that was removed? 
If so I assume someone copied it and uploaded it here?:
https://chrome.google.com/webstore/detail/youtube-dark-mode/nmbigmfjjkdbkgbnmidlkbfipnmkcpfg?utm_source=chrome-ntp-icon

**Comment by georgyangelov** [comment]
Well, it's open source, so they are free to do that :)
