### ISSUE TITLE
Not on the chrome store anymore

### ISSUE THREAD

**Issue by ajayyy** [stormbreakerbg/Dark-youtube-plugin-chrome#63]
This makes it so I have to keep re enabling it every week, did something happen?

I use the old YouTube layout.

**Comment by georgyangelov** [comment]
See https://github.com/georgyangelov/Dark-youtube-plugin-chrome/issues/61

**Comment by ajayyy** [comment]
Oh, sorry. I should have looked through the closed issues.

Thanks you for making this extension still. I will continue running it in developer mode :)

It would be awesome if you could upload it again for the people like me who hate the new design.
